store_data <- read.csv("Superstore _data.csv")
library(ggplot2)
library(tidyverse)
library(plotly)
library(lubridate)
options(scipen = 999)


store_data |>
  group_by(Category,Sub.Category) |>
  summarise(revenue = sum(Sales),
            profit = sum(Profit))-> gp_category


gp_category |> 
  mutate(grossMargin = (profit/revenue)*100) ->gp_category

ggplotly(ggplot(gp_category,aes(Category,revenue,fill = Sub.Category))+
           geom_bar(stat = "identity")+
           labs(x= "Categories", y = "Revenue",
           title = "Revenue Generated by Each Categories and Sub-Categories")+
           theme(axis.text.x = element_text(angle = 45),
                 axis.title = element_text(face = "bold"),
                 title = element_text(face = "bold",family = "Century Gothic")))


gp_category |> 
  pivot_longer(revenue:profit,
               names_to = "legend",
               values_to = "Amount")->pivot_gp_category

ggplotly(ggplot(pivot_gp_category,aes(Sub.Category,Amount,fill = legend))+
           geom_bar(stat = "identity",position = "dodge")+
           theme(axis.text.x = element_text(angle = 45))+
           labs(x= "Sub-Categories", y = "Amount",
           title = "Revenue and Gross Profit of each Sub-Categories"))

ggplotly(ggplot(pivot_gp_category |> 
                  group_by(Category,legend) |>
                  summarise(Amount = sum(Amount)),
                  aes(Category,Amount,fill  = legend))+
                  geom_bar(stat = "identity",position = "dodge")+
                  theme(axis.text.x = element_text(angle = 45),
                  title = element_text(family = "Century Gothic",face = "bold"))+
                  labs(x="Categories",y="Amount", fill = "parametres",
                  title = "Revenue and Gross Profit of each Categories"))
store_data |>
  group_by(Category) |>
  summarise(n_transactions = n())|>
  ggplot(aes(x = Category, y = n_transactions, fill = Category))+geom_col()+
  theme (axis.text.x = element_text(angle = 45))+
  labs(x="Categories",y="No.of Sales",
       title = "No.of Transactions of  Each Category")-> sales_category

ggplotly(sales_category)


store_data |>
  group_by(Sub.Category) |>
  summarise(n_transactions = n())|>
  ggplot(aes(x = Sub.Category, y = n_transactions, fill = Sub.Category))+geom_col()+
  theme (axis.text.x = element_text(angle = 45))+
  labs(x="Categories",y="No.of Sales",
       title = "No.of Transactions of  Each Sub Category")-> sales_sub_category
ggplotly(sales_sub_category)



store_data |>
  mutate(unitPrice = ifelse(Discount > "0",(Sales/Quantity)/(1-Discount),Sales/Quantity),
         subtotal = unitPrice*Quantity) |>
  group_by(Customer.ID,Customer.Name,Segment) |>
  summarise(total_revenue = sum(subtotal),
            total_orders = n_distinct(Order.ID),
            total_profit = sum(Profit)) -> customers_based


ggplotly(ggplot(customers_based |>
                  group_by(Segment) |> 
                  summarise(n_customers =  n()), 
                  aes(Segment,n_customers, fill = Segment))+
                  geom_bar(stat = "identity")+labs(x ="Segment",
                  y ="No of Customers",title = "Graph of Segment Size"))

ggplotly(ggplot(customers_based |> 
                 group_by(Segment) |> 
                 summarise(revenue = sum(total_revenue)) |>
                 mutate(revenue_percent = revenue/sum(revenue)*100),
                 aes(Segment,revenue_percent, fill = Segment))+
                 geom_bar(stat = "identity")+
                 labs(x = "Segment Names",y = "Revenue(%)",
                 title = "Revenue Percentge of Segments of Customers"))

ggplotly(ggplot(customers_based |>
                  group_by(Segment) |>
                  summarise(profits = sum(total_profit)) |> 
                  mutate(profit_percent = profits/sum(profits)*100),
                  aes(Segment,profit_percent,fill = Segment))+
                  geom_col()+labs(x="Segment Names",y="Profits(%)",
                  title = "Profits Percentage of Each segments of Customers"))

store_data |>
  mutate(order_date = strptime(Order.Date,format = "%m/%d/%Y"),
         order_year = lubridate::year(order_date),
         order_month = lubridate::month(order_date,label = TRUE, abbr = FALSE ),
         weekday = weekdays(order_date)) |>
  group_by(order_month,weekday) |> 
  summarise(n_transactions = n()) -> weekdays_trends

ggplotly(ggplot(weekdays_trends,aes(weekday,n_transactions,group = as.factor(order_month),
                                    col = as.factor(order_month)))+
            geom_line()+geom_point()+facet_wrap(~order_month)+
            labs(x="",y = "No of Transactions",
            title = "Graph of Sales in weekdays in Different Years")+
           theme(axis.text.x = element_text(angle = 45)))
  
  


                     
